const AG_GRID_LOCALE_FR = {
  // Set Filter
  selectAll: "(Sélectionner tout)",
  selectAllSearchResults: "(Sélectionner tous les résultats de la recherche)",
  addCurrentSelectionToFilter: "Ajouter la sélection actuelle au filtre",
  searchOoo: "Rechercher...",
  blanks: "(Vides)",
  noMatches: "Aucune correspondance",

  // Number Filter & Text Filter
  filterOoo: "Filtrer...",
  equals: "Égal à",
  notEqual: "Différent de",
  blank: "Vide",
  notBlank: "Non vide",
  empty: "Choisissez un",

  // Number Filter
  lessThan: "Inférieur à",
  greaterThan: "Supérieur à",
  lessThanOrEqual: "Inférieur ou égal à",
  greaterThanOrEqual: "Supérieur ou égal à",
  inRange: "Entre",
  inRangeStart: "De",
  inRangeEnd: "À",

  // Text Filter
  contains: "Contient",
  notContains: "Ne contient pas",
  startsWith: "Commence par",
  endsWith: "Se termine par",

  // Date Filter
  dateFormatOoo: "yyyy-mm-dd",
  before: "Avant",
  after: "Après",

  // Filter Conditions
  andCondition: "ET",
  orCondition: "OU",

  // Filter Buttons
  applyFilter: "Appliquer",
  resetFilter: "Réinitialiser",
  clearFilter: "Effacer",
  cancelFilter: "Annuler",

  // Filter Titles
  textFilter: "Filtre de texte",
  numberFilter: "Filtre numérique",
  dateFilter: "Filtre de date",
  setFilter: "Définir le filtre",

  // Group Column Filter
  groupFilterSelect: "Sélectionner un champ :",

  // Advanced Filter
  advancedFilterContains: "contient",
  advancedFilterNotContains: "ne contient pas",
  advancedFilterTextEquals: "égal à",
  advancedFilterTextNotEqual: "différent de",
  advancedFilterStartsWith: "commence par",
  advancedFilterEndsWith: "se termine par",
  advancedFilterBlank: "est vide",
  advancedFilterNotBlank: "n'est pas vide",
  advancedFilterEquals: "=",
  advancedFilterNotEqual: "!=",
  advancedFilterGreaterThan: ">",
  advancedFilterGreaterThanOrEqual: ">=",
  advancedFilterLessThan: "<",
  advancedFilterLessThanOrEqual: "<=",
  advancedFilterTrue: "est vrai",
  advancedFilterFalse: "est faux",
  advancedFilterAnd: "ET",
  advancedFilterOr: "OU",
  advancedFilterApply: "Appliquer",
  advancedFilterBuilder: "Constructeur",
  advancedFilterValidationMissingColumn: "Colonne manquante",
  advancedFilterValidationMissingOption: "Option manquante",
  advancedFilterValidationMissingValue: "Valeur manquante",
  advancedFilterValidationInvalidColumn: "Colonne introuvable",
  advancedFilterValidationInvalidOption: "Option introuvable",
  advancedFilterValidationMissingQuote:
    "La valeur est manquante à la fin des guillemets",
  advancedFilterValidationNotANumber: "La valeur n'est pas un nombre",
  advancedFilterValidationInvalidDate: "La valeur n'est pas une date valide",
  advancedFilterValidationMissingCondition: "Condition manquante",
  advancedFilterValidationJoinOperatorMismatch:
    "Les opérateurs de jointure dans une condition doivent être identiques",
  advancedFilterValidationInvalidJoinOperator:
    "Opérateur de jointure introuvable",
  advancedFilterValidationMissingEndBracket: "Parenthèse de fin manquante",
  advancedFilterValidationExtraEndBracket: "Trop de parenthèses de fin",
  advancedFilterValidationMessage:
    "L'expression comporte une erreur. ${variable} - ${variable}.",
  advancedFilterValidationMessageAtEnd:
    "L'expression comporte une erreur. ${variable} à la fin de l'expression.",
  advancedFilterBuilderTitle: "Filtre avancé",
  advancedFilterBuilderApply: "Appliquer",
  advancedFilterBuilderCancel: "Annuler",
  advancedFilterBuilderAddButtonTooltip: "Ajouter un filtre ou un groupe",
  advancedFilterBuilderRemoveButtonTooltip: "Supprimer",
  advancedFilterBuilderMoveUpButtonTooltip: "Déplacer vers le haut",
  advancedFilterBuilderMoveDownButtonTooltip: "Déplacer vers le bas",
  advancedFilterBuilderAddJoin: "Ajouter un groupe",
  advancedFilterBuilderAddCondition: "Ajouter un filtre",
  advancedFilterBuilderSelectColumn: "Sélectionner une colonne",
  advancedFilterBuilderSelectOption: "Sélectionner une option",
  advancedFilterBuilderEnterValue: "Entrer une valeur...",
  advancedFilterBuilderValidationAlreadyApplied:
    "Le filtre actuel est déjà appliqué.",
  advancedFilterBuilderValidationIncomplete:
    "Toutes les conditions ne sont pas remplies.",
  advancedFilterBuilderValidationSelectColumn:
    "Vous devez sélectionner une colonne.",
  advancedFilterBuilderValidationSelectOption:
    "Vous devez sélectionner une option.",
  advancedFilterBuilderValidationEnterValue: "Vous devez entrer une valeur.",

  // Side Bar
  columns: "Colonnes",
  filters: "Filtres",

  // columns tool panel
  pivotMode: "Mode Pivot",
  groups: "Groupes de lignes",
  rowGroupColumnsEmptyMessage:
    "Faites glisser ici pour définir les groupes de lignes",
  values: "Valeurs",
  valueColumnsEmptyMessage: "Faites glisser ici pour agréger",
  pivots: "Étiquettes de colonne",
  pivotColumnsEmptyMessage:
    "Faites glisser ici pour définir les étiquettes de colonne",

  // Header of the Default Group Column
  group: "Groupe",

  // Row Drag
  rowDragRow: "ligne",
  rowDragRows: "lignes",

  // Other
  loadingOoo: "Chargement...",
  loadingError: "ERR",
  noRowsToShow: "Aucune ligne à afficher",
  enabled: "Activé",

  // Menu
  pinColumn: "Épingler la colonne",
  pinLeft: "Épingler à gauche",
  pinRight: "Épingler à droite",
  noPin: "Pas d'épinglage",
  valueAggregation: "Agrégation de valeurs",
  noAggregation: "Aucune",
  autosizeThiscolumn: "Ajuster automatiquement cette colonne",
  autosizeAllColumns: "Ajuster automatiquement toutes les colonnes",
  groupBy: "Regrouper par",
  ungroupBy: "Déregrouper par",
  ungroupAll: "Déregrouper tout",
  addToValues: "Ajouter ${variable} aux valeurs",
  removeFromValues: "Supprimer ${variable} des valeurs",
  addToLabels: "Ajouter ${variable} aux étiquettes",
  removeFromLabels: "Supprimer ${variable} des étiquettes",
  resetColumns: "Réinitialiser les colonnes",
  expandAll: "Développer tous les groupes de lignes",
  collapseAll: "Réduire tous les groupes de lignes",
  copy: "Copier",
  ctrlC: "Ctrl+C",
  ctrlX: "Ctrl+X",
  copyWithHeaders: "Copier avec en-têtes",
  copyWithGroupHeaders: "Copier avec en-têtes de groupe",
  cut: "Couper",
  paste: "Coller",
  ctrlV: "Ctrl+V",
  export: "Exporter",
  csvExport: "Export CSV",
  excelExport: "Export Excel",
  columnFilter: "Filtre de colonne",
  columnChooser: "Choisir les colonnes",
  sortAscending: "Trier par ordre croissant",
  sortDescending: "Trier par ordre décroissant",
  sortUnSort: "Annuler le tri",

  // Enterprise Menu Aggregation and Status Bar
  sum: "Somme",
  first: "Premier",
  last: "Dernier",
  min: "Min",
  max: "Max",
  none: "Aucun",
  count: "Compter",
  avg: "Moyenne",
  filteredRows: "Filtré",
  selectedRows: "Sélectionné",
  totalRows: "Total des lignes",
  totalAndFilteredRows: "Lignes",
  more: "Plus",
  to: "à",
  of: "de",
  page: "Page",
  pageLastRowUnknown: "?",
  nextPage: "Page suivante",
  lastPage: "Dernière page",
  firstPage: "Première page",
  previousPage: "Page précédente",
  pageSizeSelectorLabel: "Taille de la page :",
  footerTotal: "Total",

  // Pivoting
  pivotColumnGroupTotals: "Total",

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: "Graphique Pivot & Mode Pivot",
  pivotChart: "Graphique Pivot",
  chartRange: "Plage de graphique",

  columnChart: "Histogramme",
  groupedColumn: "Groupé",
  stackedColumn: "Empilé",
  normalizedColumn: "Empilé à 100%",

  barChart: "Barre",
  groupedBar: "Groupé",
  stackedBar: "Empilé",
  normalizedBar: "Empilé à 100%",
  pieChart: "Camembert",
  pie: "Camembert",
  donut: "Donut",

  line: "Ligne",

  xyChart: "X Y (Nuage de points)",
  scatter: "Nuage de points",
  bubble: "Bulle",

  areaChart: "Zone",
  area: "Zone",
  stackedArea: "Empilée",
  normalizedArea: "Empilée à 100%",

  histogramChart: "Histogramme",
  histogramFrequency: "Fréquence",

  polarChart: "Polaire",
  radarLine: "Radar (Ligne)",
  radarArea: "Radar (Zone)",
  nightingale: "Nightingale",
  radialColumn: "Colonne radiale",
  radialBar: "Barre radiale",

  statisticalChart: "Statistique",
  boxPlot: "Boîte à moustaches",
  rangeBar: "Barre de plage",
  rangeArea: "Zone de plage",

  hierarchicalChart: "Hiérarchique",
  treemap: "Treemap",
  sunburst: "Sunburst",

  specializedChart: "Spécialisée",
  waterfall: "Cascade",
  heatmap: "Carte thermique",

  combinationChart: "Combinaison",
  columnLineCombo: "Colonnes & Lignes",
  AreaColumnCombo: "Zone & Colonnes",

  // Charts
  pivotChartTitle: "Graphique Pivot",
  rangeChartTitle: "Graphique Plage",
  settings: "Paramètres du graphique",
  data: "Données",
  format: "Format",
  categories: "Catégories",
  defaultCategory: "(Aucune)",
  series: "Séries",
  switchCategorySeries: "Changer Catégorie / Séries",
  categoryValues: "Valeurs des catégories",
  seriesLabels: "Étiquettes des séries",
  aggregate: "Agréger",
  xyValues: "Valeurs X Y",
  paired: "Mode apparié",
  axis: "Axe",
  xAxis: "Axe horizontal",
  yAxis: "Axe vertical",
  polarAxis: "Axe polaire",
  radiusAxis: "Axe de rayon",
  navigator: "Navigateur",
  zoom: "Zoom",
  animation: "Animation",
  crosshair: "Croix",
  color: "Couleur",
  thickness: "Épaisseur",
  preferredLength: "Longueur préférée",
  xType: "Type X",
  axisType: "Type d'axe",
  automatic: "Automatique",
  category: "Catégorie",
  number: "Nombre",
  time: "Temps",
  timeFormat: "Format de l'heure",
  autoRotate: "Rotation automatique",
  labelRotation: "Rotation",
  circle: "Cercle",
  polygon: "Polygone",
  orientation: "Orientation",
  fixed: "Fixé",
  parallel: "Parallèle",
  perpendicular: "Perpendiculaire",
  radiusAxisPosition: "Position",
  ticks: "Repères",
  gridLines: "Lignes de la grille",
  width: "Largeur",
  height: "Hauteur",
  length: "Longueur",
  padding: "Remplissage",
  spacing: "Espacement",
  chart: "Graphique",
  title: "Titre",
  titlePlaceholder: "Titre du graphique - double-cliquez pour éditer",
  background: "Arrière-plan",
  font: "Police",
  top: "Haut",
  right: "Droite",
  bottom: "Bas",
  left: "Gauche",
  labels: "Étiquettes",
  calloutLabels: "Étiquettes d'appel",
  sectorLabels: "Étiquettes de secteur",
  positionRatio: "Rapport de position",
  size: "Taille",
  shape: "Forme",
  minSize: "Taille minimale",
  maxSize: "Taille maximale",
  legend: "Légende",
  position: "Position",
  markerSize: "Taille du marqueur",
  markerStroke: "Contour du marqueur",
  markerPadding: "Remplissage du marqueur",
  itemSpacing: "Espacement des éléments",
  itemPaddingX: "Remplissage X des éléments",
  itemPaddingY: "Remplissage Y des éléments",
  layoutHorizontalSpacing: "Espacement horizontal",
  layoutVerticalSpacing: "Espacement vertical",
  strokeWidth: "Largeur du trait",
  offset: "Décalage",
  offsets: "Décalages",
  tooltips: "Info-bulles",
  callout: "Appel",
  markers: "Marqueurs",
  shadow: "Ombre",
  blur: "Flou",
  xOffset: "Décalage X",
  yOffset: "Décalage Y",
  lineWidth: "Largeur de la ligne",
  lineDash: "Pointillé",
  lineDashOffset: "Décalage du pointillé",
  scrollingZoom: "Défilement",
  scrollingStep: "Pas de défilement",
  selectingZoom: "Sélection",
  durationMillis: "Durée (ms)",
  crosshairLabel: "Étiquette",
  crosshairSnap: "Accrocher au nœud",
  normal: "Normal",
  bold: "Gras",
  italic: "Italique",
  boldItalic: "Gras Italique",
  predefined: "Prédéfini",
  fillOpacity: "Opacité de remplissage",
  strokeColor: "Couleur de ligne",
  strokeOpacity: "Opacité de ligne",
  miniChart: "Mini-graphique",
  histogramBinCount: "Nombre de bacs",
  connectorLine: "Ligne de connexion",
  seriesItems: "Éléments de la série",
  seriesItemType: "Type d'élément",
  seriesItemPositive: "Positif",
  seriesItemNegative: "Négatif",
  seriesItemLabels: "Étiquettes des éléments",
  columnGroup: "Colonne",
  barGroup: "Barre",
  pieGroup: "Camembert",
  lineGroup: "Ligne",
  scatterGroup: "Nuage de points",
  areaGroup: "Zone",
  polarGroup: "Polaire",
  statisticalGroup: "Statistique",
  hierarchicalGroup: "Hiérarchique",
  specializedGroup: "Spécialisée",
  combinationGroup: "Combinaison",
  groupedColumnTooltip: "Groupée",
  stackedColumnTooltip: "Empilée",
  normalizedColumnTooltip: "Empilée à 100%",
  groupedBarTooltip: "Groupée",
  stackedBarTooltip: "Empilée",
  normalizedBarTooltip: "Empilée à 100%",
  pieTooltip: "Camembert",
  donutTooltip: "Donut",
  lineTooltip: "Ligne",
  groupedAreaTooltip: "Zone",
  stackedAreaTooltip: "Empilée",
  normalizedAreaTooltip: "Empilée à 100%",
  scatterTooltip: "Nuage de points",
  bubbleTooltip: "Bulle",
  histogramTooltip: "Histogramme",
  radialColumnTooltip: "Colonne radiale",
  radialBarTooltip: "Barre radiale",
  radarLineTooltip: "Radar (Ligne)",
  radarAreaTooltip: "Radar (Zone)",
  nightingaleTooltip: "Nightingale",
  rangeBarTooltip: "Barre de plage",
  rangeAreaTooltip: "Zone de plage",
  boxPlotTooltip: "Boîte à moustaches",
  treemapTooltip: "Treemap",
  sunburstTooltip: "Sunburst",
  waterfallTooltip: "Cascade",
  heatmapTooltip: "Carte thermique",
  columnLineComboTooltip: "Colonnes & Lignes",
  areaColumnComboTooltip: "Zone & Colonnes",
  customComboTooltip: "Combinaison personnalisée",
  innerRadius: "Rayon interne",
  startAngle: "Angle de départ",
  endAngle: "Angle de fin",
  reverseDirection: "Inverser la direction",
  groupPadding: "Remplissage du groupe",
  seriesPadding: "Remplissage de la série",
  tile: "Tuile",
  whisker: "Moustache",
  cap: "Cap",
  capLengthRatio: "Rapport de longueur",
  labelPlacement: "Placement",
  inside: "Intérieur",
  outside: "Extérieur",
  noDataToChart: "Aucune donnée disponible à afficher dans le graphique.",
  pivotChartRequiresPivotMode:
    "Le graphique pivot nécessite le mode pivot activé.",
  chartSettingsToolbarTooltip: "Menu",
  chartLinkToolbarTooltip: "Lié à la grille",
  chartUnlinkToolbarTooltip: "Non lié à la grille",
  chartDownloadToolbarTooltip: "Télécharger le graphique",
  chartEdit: "Modifier le graphique",
  chartAdvancedSettings: "Paramètres avancés",
  chartLink: "Lier à la grille",
  chartUnlink: "Délier de la grille",
  chartDownload: "Télécharger le graphique",
  seriesChartType: "Type de graphique de la série",
  seriesType: "Type de série",
  secondaryAxis: "Axe secondaire",
  seriesAdd: "Ajouter une série",
  categoryAdd: "Ajouter une catégorie",
  advancedSettings: "Paramètres avancés",

  ariaAdvancedFilterBuilderItem:
    "${variable}. Niveau ${variable}. Appuyez sur ENTREE pour modifier.",
  ariaAdvancedFilterBuilderItemValidation:
    "${variable}. Niveau ${variable}. ${variable} Appuyez sur ENTREE pour modifier.",
  ariaAdvancedFilterBuilderList: "Liste de constructeur de filtre avancé",
  ariaAdvancedFilterBuilderFilterItem: "Condition de filtre",
  ariaAdvancedFilterBuilderGroupItem: "Groupe de filtre",
  ariaAdvancedFilterBuilderColumn: "Colonne",
  ariaAdvancedFilterBuilderOption: "Option",
  ariaAdvancedFilterBuilderValueP: "Valeur",
  ariaAdvancedFilterBuilderJoinOperator: "Opérateur de jonction",
  ariaAdvancedFilterInput: "Entrée de filtre avancée",
  ariaChecked: "sélectionné",
  ariaColumn: "Colonne",
  ariaColumnGroup: "Groupe de colonnes",
  ariaColumnFiltered: "Colonne filtrée",
  ariaColumnSelectAll: "Basculer la sélection de toutes les colonnes",
  ariaDateFilterInput: "Entrée de filtre de date",
  ariaDefaultListName: "Liste",
  ariaFilterColumnsInput: "Entrée de filtre de colonnes",
  ariaFilterFromValue: "Filtrer à partir de la valeur",
  ariaFilterInput: "Entrée de filtre",
  ariaFilterList: "Liste de filtres",
  ariaFilterToValue: "Filtrer jusqu'à la valeur",
  ariaFilterValue: "Valeur du filtre",
  ariaFilterMenuOpen: "Ouvrir le menu de filtre",
  ariaFilteringOperator: "Opérateur de filtrage",
  ariaHidden: "caché",
  ariaIndeterminate: "indéterminé",
  ariaInputEditor: "Éditeur d'entrée",
  ariaMenuColumn: "Appuyez sur ALT BAS pour ouvrir le menu des colonnes",
  ariaFilterColumn: "Appuyez sur CTRL ENTREE pour ouvrir le filtre",
  ariaRowDeselect: "Appuyez sur ESPACE pour désélectionner cette ligne",
  ariaRowSelectAll:
    "Appuyez sur ESPACE pour basculer la sélection de toutes les lignes",
  ariaRowToggleSelection:
    "Appuyez sur ESPACE pour basculer la sélection de ligne",
  ariaRowSelect: "Appuyez sur ESPACE pour sélectionner cette ligne",
  ariaRowSelectionDisabled:
    "La sélection de ligne est désactivée pour cette ligne",
  ariaSearch: "Recherche",
  ariaSortableColumn: "Appuyez sur ENTREE pour trier",
  ariaToggleVisibility: "Appuyez sur ESPACE pour basculer la visibilité",
  ariaToggleCellValue:
    "Appuyez sur ESPACE pour basculer la valeur de la cellule",
  ariaUnchecked: "déselectionné",
  ariaVisible: "visible",
  ariaSearchFilterValues: "Rechercher des valeurs de filtre",
  ariaPageSizeSelectorLabel: "Taille de page",
  ariaChartMenuClose: "Fermer le menu de modification du graphique",

  // Libellés ARIA pour les zones de dépôt
  ariaRowGroupDropZonePanelLabel: "Groupes de lignes",
  ariaValuesDropZonePanelLabel: "Valeurs",
  ariaPivotDropZonePanelLabel: "Étiquettes de colonnes",
  ariaDropZoneColumnComponentDescription:
    "Appuyez sur SUPPRIMER pour supprimer",
  ariaDropZoneColumnValueItemDescription:
    "Appuyez sur ENTREE pour changer le type d'agrégation",
  ariaDropZoneColumnGroupItemDescription: "Appuyez sur ENTREE pour trier",
  // utilisé pour la zone de dépôt de l'agrégation, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeparator}{column name}
  ariaDropZoneColumnComponentAggFuncSeparator: " de ",
  ariaDropZoneColumnComponentSortAscending: "croissant",
  ariaDropZoneColumnComponentSortDescending: "décroissant",

  // Libellés ARIA pour les boîtes de dialogue
  ariaLabelColumnMenu: "Menu de colonne",
  ariaLabelColumnFilter: "Filtre de colonne",
  ariaLabelCellEditor: "Éditeur de cellule",
  ariaLabelDialog: "Boîte de dialogue",
  ariaLabelSelectField: "Sélectionner le champ",
  ariaLabelRichSelectField: "Sélectionner le champ riche",
  ariaLabelTooltip: "Info-bulle",
  ariaLabelContextMenu: "Menu contextuel",
  ariaLabelSubMenu: "Sous-menu",
  ariaLabelAggregationFunction: "Fonction d'agrégation",
  ariaLabelAdvancedFilterAutocomplete: "Suggestion de filtre avancé",
  ariaLabelAdvancedFilterBuilderAddField:
    "Ajouter un champ au constructeur de filtre avancé",
  ariaLabelAdvancedFilterBuilderColumnSelectField:
    "Sélectionner le champ de colonne du constructeur de filtre avancé",
  ariaLabelAdvancedFilterBuilderOptionSelectField:
    "Sélectionner le champ d'option du constructeur de filtre avancé",
  ariaLabelAdvancedFilterBuilderJoinSelectField:
    "Sélectionner le champ d'opérateur de jonction du constructeur de filtre avancé",

  // Libellés ARIA pour la barre latérale
  ariaColumnPanelList: "Liste de colonnes",
  ariaFilterPanelList: "Liste de filtres",

  // Format numérique (barre d'état, panneau de pagination)
  thousandSeparator: ",",
  decimalSeparator: ".",

  // Types de données
  true: "Vrai",
  false: "Faux",
  invalidDate: "Date non valide",
  invalidNumber: "Nombre non valide",
  january: "Janvier",
  february: "Février",
  march: "Mars",
  april: "Avril",
  may: "Mai",
  june: "Juin",
  july: "Juillet",
  august: "Août",
  september: "Septembre",
  october: "Octobre",
  november: "Novembre",
  december: "Décembre",

  // Formats horaires
  timeFormatSlashesDDMMYYYY: "JJ/MM/AAAA",
  timeFormatSlashesMMDDYYYY: "MM/JJ/AAAA",
  timeFormatSlashesDDMMYY: "JJ/MM/AA",
  timeFormatSlashesMMDDYY: "MM/JJ/AA",
  timeFormatDotsDDMYY: "JJ.M.AA",
  timeFormatDotsMDDYY: "M.JJ.AA",
  timeFormatDashesYYYYMMDD: "AAAA-MM-JJ",
  timeFormatSpacesDDMMMMYYYY: "JJ MMMM AAAA",
  timeFormatHHMMSS: "HH:MM:SS",
  timeFormatHHMMSSAmPm: "HH:MM:SS AM/PM",
};

const AG_GRID_LOCALE_ZZZ = {};
// Create a dummy locale based on english but prefix everything with zzz
Object.keys(AG_GRID_LOCALE_FR).forEach(function (key) {
  if (key === "thousandSeparator" || key === "decimalSeparator") {
    return;
  }
  AG_GRID_LOCALE_ZZZ[key] = "zzz-" + AG_GRID_LOCALE_FR[key];
});
